# Generated by Django 4.2.23 on 2025-07-05 10:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_customuser_is_api_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal name for this checkout page', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug for the checkout page', max_length=200, unique=True)),
                ('title', models.CharField(help_text='Page title displayed to customers', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description displayed on checkout page')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='checkout_logos/')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Secondary brand color (hex)', max_length=7)),
                ('background_color', models.CharField(default='#F8FAFC', help_text='Background color (hex)', max_length=7)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('allow_custom_amount', models.BooleanField(default=True, help_text='Allow customers to enter custom amounts')),
                ('is_active', models.BooleanField(default=True)),
                ('require_customer_info', models.BooleanField(default=True, help_text='Require customer email and name')),
                ('require_billing_address', models.BooleanField(default=False, help_text='Require billing address')),
                ('require_shipping_address', models.BooleanField(default=False, help_text='Require shipping address')),
                ('success_url', models.URLField(blank=True, help_text='Redirect URL after successful payment')),
                ('cancel_url', models.URLField(blank=True, help_text='Redirect URL after cancelled payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.preferredcurrency')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_pages', to='authentication.merchant')),
            ],
            options={
                'verbose_name': 'Checkout Page',
                'verbose_name_plural': 'Checkout Pages',
                'ordering': ['-created_at'],
                'unique_together': {('merchant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('selected_payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='checkout.checkoutpage')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.preferredcurrency')),
            ],
            options={
                'verbose_name': 'Checkout Session',
                'verbose_name_plural': 'Checkout Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('gateway_config', models.JSONField(blank=True, default=dict, help_text='Gateway-specific configuration')),
                ('display_name', models.CharField(blank=True, help_text='Custom display name', max_length=100)),
                ('icon_override', models.ImageField(blank=True, null=True, upload_to='payment_method_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='checkout.checkoutpage')),
            ],
            options={
                'verbose_name': 'Payment Method Configuration',
                'verbose_name_plural': 'Payment Method Configurations',
                'ordering': ['display_order', 'payment_method'],
                'unique_together': {('checkout_page', 'payment_method')},
            },
        ),
    ]
