# Generated by Django 4.2.23 on 2025-07-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator'), ('staff', 'Staff')], max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that users with this role will automatically inherit', related_name='role_mappings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Role Group Mapping',
                'verbose_name_plural': 'Role Group Mappings',
                'ordering': ['role'],
            },
        ),
    ]
