# Generated by Django 4.2.23 on 2025-07-04 04:21

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merchantcategory_merchant_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('bank_statement', 'Bank Statement'), ('identity_document', 'Identity Document'), ('business_registration', 'Business Registration'), ('utility_bill', 'Utility Bill'), ('insurance_certificate', 'Insurance Certificate'), ('financial_statement', 'Financial Statement'), ('other', 'Other')], help_text='Type of document being uploaded', max_length=50)),
                ('document_file', models.FileField(help_text='Upload the document file (PDF, JPG, PNG supported)', upload_to=authentication.models.merchant_document_upload_path)),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('title', models.CharField(help_text='Document title or description', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about the document')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this document is required for merchant verification')),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date (if applicable)', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from the verification process')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the document was verified', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File MIME type', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.merchant')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Document',
                'verbose_name_plural': 'Merchant Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('merchant', 'document_type', 'title')},
            },
        ),
    ]
