# Generated by Django 4.2.23 on 2025-07-04 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merchantdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the document type', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Internal code for the document type', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this document type is for')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this document type is required for merchant verification')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document type is available for upload')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this document type (lower numbers first)')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class for displaying this document type', max_length=50)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum file size allowed in MB')),
                ('allowed_extensions', models.CharField(default='.pdf,.jpg,.jpeg,.png,.doc,.docx', help_text='Comma-separated list of allowed file extensions', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
