# Generated by Django 4.2.23 on 2025-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_app_key_generation_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_api_user',
            field=models.BooleanField(default=False, help_text='Whether this user was created for API key authentication'),
        ),
    ]
