# Generated by Django 4.2.23 on 2025-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredcurrency',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='preferredcurrency',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
