# Generated by Django 4.2.23 on 2025-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gaming Peripherals', 'Gaming Peripherals'), ('Gaming Audio', 'Gaming Audio'), ('Gaming Furniture', 'Gaming Furniture'), ('Gaming Displays', 'Gaming Displays'), ('Gaming Hardware', 'Gaming Hardware'), ('Gaming Accessories', 'Gaming Accessories'), ('Gaming Streaming', 'Gaming Streaming'), ('Gaming Controllers', 'Gaming Controllers'), ('Gaming Storage', 'Gaming Storage'), ('Gaming Memory', 'Gaming Memory'), ('Gaming VR', 'Gaming VR'), ('Gaming Cooling', 'Gaming Cooling')], default='Gaming Accessories', max_length=50),
        ),
    ]
