# Generated by Django 4.2.23 on 2025-08-01 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('bank', 'Bank Integration'), ('payment_gateway', 'Payment Gateway'), ('sms', 'SMS Service'), ('email', 'Email Service'), ('kyc', 'KYC/Identity Verification'), ('accounting', 'Accounting Software'), ('crm', 'Customer Relationship Management'), ('analytics', 'Analytics Platform'), ('uba_bank', 'UBA Bank Integration'), ('cybersource', 'CyberSource Payment Gateway'), ('corefy', 'Corefy Payment Platform'), ('stripe', 'Stripe Payment Gateway'), ('paypal', 'PayPal Integration'), ('flutterwave', 'Flutterwave Payment Gateway'), ('paystack', 'Paystack Payment Gateway'), ('mpesa', 'M-Pesa Mobile Money'), ('blockchain', 'Blockchain Integration'), ('ai_service', 'AI/ML Service'), ('logistics', 'Logistics Provider'), ('social_media', 'Social Media Platform'), ('messaging', 'Messaging Service'), ('custom_api', 'Custom API Integration'), ('other', 'Other Integration')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_config', models.JSONField(default=dict, help_text='Provider-specific configuration and capabilities')),
                ('endpoints', models.JSONField(default=dict, help_text='API endpoints mapping for different operations')),
                ('supported_operations', models.JSONField(default=list, help_text='List of supported operations for this provider')),
                ('fee_structure', models.JSONField(default=dict, help_text='Fee structure for different operations')),
                ('limits', models.JSONField(default=dict, help_text='Transaction limits and constraints')),
                ('webhook_config', models.JSONField(default=dict, help_text='Webhook configuration and event types')),
                ('sandbox_config', models.JSONField(default=dict, help_text='Sandbox environment specific configuration')),
                ('production_config', models.JSONField(default=dict, help_text='Production environment specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_config', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Integration Provider',
                'verbose_name_plural': 'Integration Providers',
                'ordering': ['integration__provider_name'],
            },
        ),
    ]
